version: 2
updates:
# Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
# Maintain dependencies for golang
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
    time: "12:00" # 12pm UTC
# Maintain dependencies for Dockerfile
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
