apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: playground
build:
  artifacts:
  - image: jacodelg/inventory
    context: cmd/inventory
    docker:
      dockerfile: Dockerfile
  - image: jacodelg/storefront
    context: cmd/storefront
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/inventory/deployment.yaml
    - k8s/inventory/namespace.yaml
    - k8s/inventory/service.yaml
    - k8s/inventory/serviceaccount.yaml
    - k8s/storefront/deployment.yaml
    - k8s/storefront/namespace.yaml
    - k8s/storefront/service.yaml
    - k8s/storefront/serviceaccount.yaml
