apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: inventory
build:
  artifacts:
  - image: jacodelg/inventory
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/namespace.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/serviceaccount.yaml
