apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
  labels:
    app: playground
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: jacodelg/playground:latest
        ports:
        - name: http
          containerPort: 8090
          protocol: TCP
          appProtocol: http
        - name: grpc
          containerPort: 8000
          protocol: TCP
          appProtocol: grpc
      serviceAccountName: playground
