apiVersion: v1
kind: Service
metadata:
  name: playground
  labels:
    app: playground
    service: playground
spec:
  ports:
    - name: http
      appProtocol: http
      port: 80
      targetPort: 8090
  selector:
    app: playground