apiVersion: v1
kind: Service
metadata:
  name: storefront
  namespace: storefront
  labels:
    app: storefront
    service: storefront
spec:
  ports:
  - name: http
    appProtocol: http
    port: 80
    targetPort: 8090
  - name: grpc
    appProtocol: grpc
    port: 81
    targetPort: 8000
  selector:
    app: storefront