apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: inventory
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: jacodelg/inventory:latest
        ports:
        - name: http
          containerPort: 8090
          protocol: TCP
        - name: grpc
          containerPort: 8000
          protocol: TCP
      serviceAccountName: inventory
